### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by LukasHedegaard** [LukasHedegaard/continual-inference#24]
The project doesn't supply any documentation other than the README (and the code itself).

Before Reaching v1.0.0, this is an absolute must-have.

**Comment by itsRoman** [comment]
May I abuse this issue to just drop a quick appreciation?

Great (and actually useful) idea + high code quality, keep up the good work!

And yes, a documentation at some point would be great ;)

**Comment by LukasHedegaard** [comment]
Thanks, appreciations are always welcome 🙏 
I am planning on adding docs pretty soon, though other work seems to keep cutting in line time and time again.
I'll keep you updated :-)

**Comment by LukasHedegaard** [comment]
Docs added in #45 . Moreover, an article was published, which gives a comprehensive introduction to the library design: 
[Continual Inference: A Library for Efficient Online Inference with Deep Neural Networks in PyTorch](https://arxiv.org/abs/2204.03418)
