### ISSUE TITLE
TorchScript support

### ISSUE THREAD

**Issue by itsRoman** [LukasHedegaard/continual-inference#47]
Hi,

are there any plans to make the continual model (i.e. with call_mode == "forward_step") exportable as TorchScript?
My use case would be using the framework in a C++ environment.
I guess the TensorPlaceholder concept would need to be changed?

Best

**Comment by LukasHedegaard** [comment]
That would indeed be a nice feature. I'll make a note of it and see if I find the time at some point. 
Of course, PR's are more than welcome as well :-)

**Comment by LukasHedegaard** [comment]
As of version 1.0.0, all modules can be exported to ONNX (see [examples](https://github.com/LukasHedegaard/continual-inference/blob/main/tests/continual/test_onnx.py)). This includes conversions with `torch.jit.trace`.

Note however, that the traced module is not able to handle the dynamic routes during start-up. While it is possible to modify the library to handle `torch.jit.script` and dynamic routing, this is a cumbersome process that would require a substantial modification of all modules to use only the Python subset compatible with TorchScript. We can achieve the desired inference behaviour without doing so (using a the `_forward_step` function of a module, and passing initialised states in explicitly). Moreover, dynamic behaviour is not supported by ONNX. Accordingly, I do not plan on modifying the library unless substantial pressure builds up from the community 😊
