### ISSUE TITLE
Auto shrink

### ISSUE THREAD

**Issue by SeanBtmn** [LukasHedegaard/continual-inference#62]
Hi there again,

is this actually correct?

https://github.com/LukasHedegaard/continual-inference/blob/a7c84b87ce21ec968127006bb0637c8e81747c86/continual/delay.py#L134

For my understanding it does not make sense that for auto_shrink="lagging" we throw away self.delay samples, but for auto_shrink="centered" we throw away 2*self.delay samples?!

I also think a third option 

```
if self.auto_shrink == "online":
    return input[:, :, self.delay:]
```

would make sense, at least I could use it ;)

**Comment by LukasHedegaard** [comment]
I think you are right - the implementation doesn’t cover all cases. The current implementation of centered residuals had convolutions with equal padding in mind (padding reduces delay), while the lagging implementation was for situations without padding. I’m not sure the proposed “online” mode would work out, though. Rather, the “centered” should be updated to handle cases without padding as well. I’ll make a note and get to it before long.

**Comment by SeanBtmn** [comment]
Ah, I thought they were meant to be exchangeable - makes sense then.

I have a residual structure like

ABCDE -> conv (kernel 3, no padding) ->  FGH
   |                                                                                              ---> output = FGH + CDE
    ---------> residual conn. (cuts off 'AB') -> CDE

Since in the end I only care about the current timestep (i.e. the 'E' part in the input data) I throw away the data farthest in the past in the residual connection.

I'd like to train this in call_mode = 'forward' and then do inference with 'forward_step'. 
This could be done with the proposed auto_shrink="online", if I don't have a fundamental misunderstanding (which is quite possible).

**Comment by LukasHedegaard** [comment]
OK, I think I know what you're going for.
If you compare with figures 4 and 5 in https://arxiv.org/pdf/2204.03418.pdf, the situation you describe would look like this:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/6731186/221501888-e618ffbb-32b1-4002-af94-6fd4b724a11f.png">
The left-hand side would the regular forward mode, and the right-hand side the step inference mode.
Is this correct?

**Comment by SeanBtmn** [comment]
Exactly!

**Comment by LukasHedegaard** [comment]
Hi Sean, I've added a "leading" mode in the `Residual` functor. It uses a new `Skip` module, which skips a number of steps. The associated unit-test is found [here](https://github.com/LukasHedegaard/continual-inference/blob/95e65df0be941b655d38a3965db1cc0503c97f25/tests/continual/test_container.py#L325).

Let me know if you face issues using it.
