### ISSUE TITLE
Clear memory

### ISSUE THREAD

**Issue by madrigall** [LukasHedegaard/continual-inference#63]
Hi @LukasHedegaard,

Is there any way to quickly reset the memory when I change the visual context, for example, I fed one video as input and then changed it to another. At the same time I want to reset the delay and ignore the previous context. 
Should I fill this delay with empty frames? Forgive me in advance if I missed it in the documentation.

Thank you

**Comment by LukasHedegaard** [comment]
Don't worry @madrigall . It's mentioned briefly in the [paper](https://arxiv.org/pdf/2204.03418.pdf), but you are right -  it's not clear enough in the documentation.
To reset the network, you can simply call `net.clean_state()`.
I'll put the update of the docs on my todo-list and close this issue when the docs have been updated.

**Comment by madrigall** [comment]
Thank you, @LukasHedegaard

**Comment by LukasHedegaard** [comment]
@madrigall , the README and docs were updated with some instructions on module state.
